name: Archive feature branch (after merge)

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  
jobs:
  call-archive-workflow:
    uses: markusroessler/Github.Actions.Workflows/.github/workflows/archive-feature-branch.yml@v1
    with:
      git-branch: ${{ github.head_ref }}